config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create]

  get 'signup', to: 'users#new', as: 'signup'
  get 'show_qr', to: 'users#show_qr', as: 'show_qr'
  post 'qr_setup', to: 'users#qr_setup', as: 'qr_setup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true

  def generate_token
    begin
      self.token = ROTP::Base32.random
    end while self.class.exists?(token: token)
  end

  def qr_code
    _qrcode = RQRCode::QRCode.new(totp)
  end

  def totp
    totp = ROTP::TOTP.new(self.token, issuer: "My service")
    result = totp.provisioning_uri('localhost:3000')

    return result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    totp = ROTP::TOTP.new(user.token) if user
    if user && user.authenticate(params[:password]) && totp.now.eql?(params[:authentication_code])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:alert] = "Email, password or authentication_code wrong"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :show_qr, :qr_setup, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@token = @user.qr_code
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.generate_token

    respond_to do |format|
      if @user.save
        format.html { redirect_to show_qr_path(id: @user.id) }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        flash[:alert] = "Something went wrong, try again"
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_qr
    @qr_code = @user.qr_code
  end

  def qr_setup
    totp = ROTP::TOTP.new(@user.token)
    if totp.now.eql?(params[:authentication_code])
      redirect_to login_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to root_path
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="mt-3 text-center">Welcome</h1>

<div class="mt-3 text-center">
  <% if current_user %>
    Logged in as <%= current_user.email %>
      <h3 class="mt-2">
        <%= link_to('Log Out', logout_path, class: 'badge badge-light') %>
      </h3>

  <% else %>
    <h1>
      <%= link_to('Log In', login_path, class: 'badge badge-light')%> or
      <%= link_to('Sign Up', signup_path, class: 'badge badge-light') %>
    </h1>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UpTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="row">
    <div class="col-4 offset-4 border border-secondary p-5 bg-light">
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="text-center">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="mt-3 text-center">New User</h1>

<%= render 'form', user: @user %>

<div class='text-center mt-3'>
    <%= link_to 'Back', root_path, class: 'btn btn-info'  %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_qr.html.erb
<h1 class="mt-3 text-center col-5 offset-3 ">Now Set up 2nd factor authenticate</h1>
  <div class="row">
    <div class="col-5 offset-3 border border-secondary p-5 bg-light">
      <div class="qr_code text-center">
        <%= raw @qr_code.as_svg(module_size: 3) %>
      </div>


      <%= form_with(url: qr_setup_path(id: @user.id)) do |form|%>
        <div class="field">
          <%= form.label :authentication_code, class: 'd-block mt-2 text-center' %>
          <%= form.password_field :authentication_code, class: 'form-control' %>
        </div>

        <div class='text-center mt-3'>
           <%= form.submit 'Save', class: 'btn btn-primary w-25'%>
        </div>
    </div>
  </div>
<% end %>